// ---------------------------------------------------------------------------
// All content lives here. In-memory only; no backend.
// Source: RAKEZ KPI Dashboard — Build Specification (Acquisition & Brand
// Scorecard). Baselines are the spec's Sep 2026 figures from the GIP III
// evidence; '—' means RAKEZ must supply the figure. Peer benchmark values are
// illustrative and flagged as such. Nothing here reads RAKEZ systems.
// ---------------------------------------------------------------------------

export const BRAND = {
  name: 'RAKEZ Scorecard',
  accent: 'RAKEZ',
  greeting: 'Welcome',
  title: 'RAKEZ · Acquisition & Brand Scorecard',
  tagline: 'Is acquisition lifting the brand, or just buying it?',
  pitch:
    'A monthly one-page balanced scorecard for RAKEZ commercial leadership. Three hero numbers, sixteen tiles and one benchmark chart track whether the acquisition strategy lifts brand equity while defending best-in-class conversion.',
  primaryCta: '📊 Back to the scorecard',
  secondaryCta: '🧭 Personalise my view',
  footnote:
    'Demo mode — indicative Sep 2026 baselines from GIP III evidence; peer values illustrative. Static mock-up: it does not read RAKEZ systems. Unsourced KPIs show a dash, never a placeholder number.',
  generatingTitle: 'Assembling your scorecard view…',
  generatingDetail: 'Loading Sep 2026 baselines, mapping owners to tiles, sequencing the pilot plan.',
  period: 'Sep 2026',
  periodPill: 'Baseline Sep 2026',
  guardrail: 'Static mock-up — reads no RAKEZ data; unsourced KPIs show a dash, never a placeholder number.',
}

export const QUESTIONS = [
  {
    id: 'role',
    title: 'Which seat are you in?',
    subtitle: 'Your tiles get a marker and a one-tap filter.',
    options: [
      { value: 'leadership', label: 'Commercial leadership', emoji: '🧭' },
      { value: 'channel', label: 'Channel team', emoji: '🤝' },
      { value: 'salesops', label: 'Sales ops', emoji: '📞' },
      { value: 'marketing', label: 'Marketing', emoji: '📣' },
      { value: 'finance', label: 'Finance', emoji: '💰' },
    ],
  },
  {
    id: 'cadence',
    title: 'How often will you open this?',
    subtitle: 'Sets which tiles lead your view.',
    options: [
      { value: 'weekly', label: 'Weekly — the two SLA tiles', emoji: '⚡' },
      { value: 'monthly', label: 'Monthly — the full refresh', emoji: '📅' },
      { value: 'quarterly', label: 'Quarterly — mystery shop & re-score', emoji: '🔬' },
    ],
  },
  {
    id: 'focus',
    title: 'What must move this quarter?',
    subtitle: 'Puts one hero number in the spotlight.',
    options: [
      { value: 'HERO_01', label: 'Lift the Brand Equity Score', emoji: '🏛️' },
      { value: 'HERO_02', label: 'Lift the Google rating', emoji: '⭐' },
      { value: 'HERO_03', label: 'Defend enquiry → registration', emoji: '🎯' },
    ],
  },
]

export const ROLE_META = {
  leadership: { label: 'Commercial leadership', owners: null, icon: '🧭' },
  channel: { label: 'Channel team', owners: ['Channel'], icon: '🤝' },
  salesops: { label: 'Sales ops', owners: ['Sales ops'], icon: '📞' },
  marketing: { label: 'Marketing', owners: ['Marketing', 'Marketing + Sales'], icon: '📣' },
  finance: { label: 'Finance', owners: ['Finance'], icon: '💰' },
}

export const CADENCE_META = {
  weekly: { label: 'Weekly', match: ['Weekly'], note: 'Sales ops updates the two SLA tiles every week.' },
  monthly: { label: 'Monthly', match: ['Monthly', 'Weekly'], note: 'Full refresh by the 5th working day; 30-minute review with commercial leadership.' },
  quarterly: { label: 'Quarterly', match: ['Quarterly', 'Annual (quarterly during pilot)'], note: 'Partner mystery shop and Brand Equity re-score.' },
}

export const QUADRANTS = [
  { id: 'customer', label: 'Customer', icon: '🧑‍💼', blurb: 'Do prospects and partners choose RAKEZ on value?' },
  { id: 'process', label: 'Internal Process', icon: '⚙️', blurb: 'Is the first quote honest and fast?' },
  { id: 'financial', label: 'Financial', icon: '💰', blurb: 'Is growth paid for sustainably?' },
  { id: 'learning', label: 'Learning & Growth', icon: '🌱', blurb: 'Are people, partners and content improving?' },
]

// Rule kinds (engine.js):
//  higher  – numeric, higher is better: < red → red, < amber → amber, else green
//  zero    – 0 is green, anything else red (reactive price cuts)
//  sign    – negative red, zero amber, positive green (net tier movement)
//  nonneg  – negative red, otherwise green (revenue vs prior quarter)
//  pending – stays amber until thresholds exist (cost per SME)
//  claimed – Trustpilot: unclaimed red; claimed < 3.8 amber; ≥ 3.8 green
export const KPIS = [
  // ---- Hero row -----------------------------------------------------------
  {
    id: 'HERO_01',
    quadrant: 'hero',
    icon: '🏛️',
    label: 'Indicator Brand Equity Score',
    short: 'BE score',
    definition: 'Σ(dimension score × weight) ÷ 5 × 100; five dimensions per Appendix B rules.',
    source: 'Re-scoring worksheet (spec §6)',
    sourceId: 'be-rescoring',
    owner: 'Marketing',
    freq: 'Annual (quarterly during pilot)',
    baseline: { display: '48', value: 48 },
    target: { display: '70', value: 70 },
    thresholds: '<55 red; 55–65 amber; ≥65 green',
    rule: { kind: 'higher', red: 55, amber: 65 },
    scale: { min: 0, max: 100, unit: '/100' },
    input: { type: 'range', min: 0, max: 100, step: 1, label: 'Composite score (0–100)' },
    signal: 'Re-score in the BE worksheet, then apply here.',
  },
  {
    id: 'HERO_02',
    quadrant: 'hero',
    icon: '⭐',
    label: 'Google rating',
    short: 'Google rating',
    definition: 'Aggregate star rating on the RAKEZ Google Business Profile.',
    source: 'Google Business Profile',
    sourceId: 'gbp',
    owner: 'Marketing',
    freq: 'Monthly',
    baseline: { display: '3.7', value: 3.7, detail: '520 reviews' },
    target: { display: '4.3', value: 4.3 },
    thresholds: '<4.0 red; 4.0–4.2 amber; ≥4.3 green',
    rule: { kind: 'higher', red: 4.0, amber: 4.3 },
    scale: { min: 0, max: 5, unit: '★' },
    input: { type: 'range', min: 1, max: 5, step: 0.1, label: 'Aggregate rating (1–5)' },
    signal: '520 reviews at baseline.',
  },
  {
    id: 'HERO_03',
    quadrant: 'hero',
    icon: '🎯',
    label: 'Enquiry → registration conversion',
    short: 'Conversion',
    definition: 'Registrations ÷ qualified enquiries, SME funnel, trailing 3 months.',
    source: 'CRM',
    sourceId: 'crm',
    owner: 'Sales ops',
    freq: 'Monthly',
    baseline: { display: '~8%', value: 8, detail: 'best-in-class' },
    target: { display: '+1 pt (≥9%)', value: 9 },
    thresholds: 'Below baseline red; at baseline amber; ≥ +1 pt green',
    rule: { kind: 'higher', red: 8, amber: 9 },
    scale: { min: 0, max: 12, unit: '%' },
    input: { type: 'range', min: 0, max: 12, step: 0.5, label: 'Conversion, trailing 3 months (%)' },
    signal: 'Best-in-class — a position to defend.',
  },
  // ---- Customer ------------------------------------------------------------
  {
    id: 'CUST_01',
    quadrant: 'customer',
    icon: '🗣️',
    label: 'Unprompted CSP recommendation rate',
    short: 'CSP recommends RAKEZ',
    definition: '% of partner mystery-shop calls where RAKEZ is named before the prospect names it.',
    source: 'Quarterly partner mystery shop (spec §7)',
    sourceId: 'mystery-shop',
    owner: 'Channel',
    freq: 'Quarterly',
    baseline: { display: '0%', value: 0, detail: '0 of 2' },
    target: { display: '40%', value: 40 },
    thresholds: '<20 red; 20–39 amber; ≥40 green',
    rule: { kind: 'higher', red: 20, amber: 40 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 5, label: 'Calls naming RAKEZ first (%)' },
    signal: '0 of 2 partners named RAKEZ unprompted.',
  },
  {
    id: 'CUST_02',
    quadrant: 'customer',
    icon: '🏷️',
    label: 'Website vs CSP price match',
    short: 'Price match',
    definition: '% of audited quotes equal to the published price of record for the same package.',
    source: 'Monthly quote audit (10 random enquiries)',
    sourceId: 'quote-audit',
    owner: 'Marketing + Sales',
    freq: 'Monthly',
    baseline: { display: 'No', value: 0, detail: 'AED 6k vs 12k' },
    target: { display: '100%', value: 100 },
    thresholds: '<80 red; 80–99 amber; 100 green',
    rule: { kind: 'higher', red: 80, amber: 100 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 10, label: 'Audited quotes matching price of record (%)' },
    signal: 'CSP quoted AED 6k against a AED 12k price of record.',
  },
  {
    id: 'CUST_03',
    quadrant: 'customer',
    icon: '🛡️',
    label: 'Trustpilot profile',
    short: 'Trustpilot',
    definition: 'Claimed status and rating.',
    source: 'Trustpilot',
    sourceId: 'trustpilot',
    owner: 'Marketing',
    freq: 'Monthly',
    baseline: { display: '2.6', value: 2.6, detail: 'unclaimed' },
    target: { display: 'Claimed; ≥3.8', value: 3.8 },
    thresholds: 'Unclaimed red; claimed <3.5 amber; ≥3.8 green',
    rule: { kind: 'claimed', amber: 3.5, green: 3.8 },
    scale: { min: 0, max: 5, unit: '★' },
    input: { type: 'range', min: 1, max: 5, step: 0.1, label: 'Trustpilot rating (1–5)' },
    signal: 'Claiming the profile alone moves the tile from red to amber.',
  },
  {
    id: 'CUST_04',
    quadrant: 'customer',
    icon: '🧩',
    label: 'Share of new UAE registrations',
    short: 'Registration share',
    definition: 'RAKEZ new registrations ÷ UAE free-zone total.',
    source: 'Internal + industry data',
    sourceId: 'industry-data',
    owner: 'Strategy',
    freq: 'Quarterly',
    baseline: { display: '~19%', value: 19 },
    target: { display: 'Hold ≥19%', value: 19 },
    thresholds: '<18 red; 18–19 amber; ≥19 green',
    rule: { kind: 'higher', red: 18, amber: 19 },
    scale: { min: 0, max: 30, unit: '%' },
    input: { type: 'range', min: 10, max: 30, step: 0.5, label: 'Share of new UAE free-zone registrations (%)' },
    signal: 'A position to defend.',
  },
  // ---- Internal process ----------------------------------------------------
  {
    id: 'PROC_01',
    quadrant: 'process',
    icon: '🧾',
    label: 'Extras disclosed at first quote',
    short: 'Extras disclosed',
    definition: 'Of 5 standard extras (banker fee, insurance, tax reg, filing, 2nd visa), how many appear on the first written quote.',
    source: 'Quote audit',
    sourceId: 'quote-audit',
    owner: 'Sales ops',
    freq: 'Monthly',
    baseline: { display: '0 / 5', value: 0 },
    target: { display: '5 / 5', value: 5 },
    thresholds: '<3 red; 3–4 amber; 5 green',
    rule: { kind: 'higher', red: 3, amber: 5 },
    scale: { min: 0, max: 5, unit: '/5' },
    input: { type: 'count', max: 5, label: 'Extras on the first written quote' },
    signal: 'Banker fee · insurance · tax registration · filing · 2nd visa.',
  },
  {
    id: 'PROC_02',
    quadrant: 'process',
    icon: '☎️',
    label: 'Call answered ≤ 3 rings',
    short: 'Call ≤3 rings',
    definition: '% inbound sales calls answered within 3 rings.',
    source: 'Telephony log',
    sourceId: 'telephony',
    owner: 'Sales ops',
    freq: 'Weekly',
    baseline: { display: '—', value: null },
    target: { display: '≥90%', value: 90 },
    thresholds: '<75 red; 75–89 amber; ≥90 green',
    rule: { kind: 'higher', red: 75, amber: 90 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 1, label: 'Calls answered within 3 rings (%)' },
    signal: 'Not yet measured — export the telephony log weekly.',
  },
  {
    id: 'PROC_03',
    quadrant: 'process',
    icon: '⏱️',
    label: 'All-in quote ≤ 15 min',
    short: 'Quote ≤15 min',
    definition: '% enquiries receiving the all-in quote within 15 minutes.',
    source: 'CRM timestamps',
    sourceId: 'crm',
    owner: 'Sales ops',
    freq: 'Weekly',
    baseline: { display: '—', value: null },
    target: { display: '≥80%', value: 80 },
    thresholds: '<60 red; 60–79 amber; ≥80 green',
    rule: { kind: 'higher', red: 60, amber: 80 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 1, label: 'Enquiries quoted all-in within 15 min (%)' },
    signal: 'Not yet measured — needs the quote-sent timestamp.',
  },
  {
    id: 'PROC_04',
    quadrant: 'process',
    icon: '📅',
    label: 'Compliance alerts ≥ 30 days ahead',
    short: 'Compliance alerts',
    definition: '% clients notified of corporate-tax registration / renewal / penalty deadlines ≥30 days before.',
    source: 'Compliance system',
    sourceId: 'compliance',
    owner: 'Compliance',
    freq: 'Monthly',
    baseline: { display: 'Ad hoc', value: 0 },
    target: { display: '100%', value: 100 },
    thresholds: '<90 red; 90–99 amber; 100 green',
    rule: { kind: 'higher', red: 90, amber: 100 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 1, label: 'Clients alerted ≥30 days ahead (%)' },
    signal: 'No systematic notification today.',
  },
  // ---- Financial -----------------------------------------------------------
  {
    id: 'FIN_01',
    quadrant: 'financial',
    icon: '🧮',
    label: 'Cost per acquired SME',
    short: 'Cost per SME',
    definition: '(Marketing + commission + sales cost) ÷ SME registrations.',
    source: 'Finance',
    sourceId: 'finance',
    owner: 'Finance',
    freq: 'Monthly',
    baseline: { display: '—', value: null },
    target: { display: 'Trend down vs Ajman/IFZA benchmark', value: null },
    thresholds: 'Set after 3 months of data',
    rule: { kind: 'pending' },
    scale: { min: 0, max: 20000, unit: 'AED' },
    input: { type: 'number', min: 0, max: 50000, step: 100, label: 'Cost per acquired SME (AED)' },
    signal: 'Thresholds are set after three months of data.',
  },
  {
    id: 'FIN_02',
    quadrant: 'financial',
    icon: '🤝',
    label: 'Commission cost per registration',
    short: 'Commission at renewal',
    definition: 'Total partner commission ÷ partner-sourced registrations; % paid at renewal.',
    source: 'Finance + channel',
    sourceId: 'finance',
    owner: 'Channel',
    freq: 'Monthly',
    baseline: { display: '—', value: null },
    target: { display: '≥30% retention-linked by month 9', value: 30 },
    thresholds: '<10 red; 10–29 amber; ≥30 green',
    rule: { kind: 'higher', red: 10, amber: 30 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 5, label: 'Commission paid at renewal (%)' },
    signal: 'Tracks the share of commission paid at renewal.',
  },
  {
    id: 'FIN_03',
    quadrant: 'financial',
    icon: '📈',
    label: 'First-year revenue per SME',
    short: 'Revenue per SME',
    definition: 'Licence + visa + facility + services billed in first 12 months ÷ SME registrations.',
    source: 'Finance',
    sourceId: 'finance',
    owner: 'Finance',
    freq: 'Quarterly',
    baseline: { display: '—', value: null },
    target: { display: 'Hold or grow', value: 0 },
    thresholds: 'Below prior quarter red',
    rule: { kind: 'nonneg' },
    scale: { min: -20, max: 20, unit: '% vs prior qtr' },
    input: { type: 'range', min: -20, max: 20, step: 1, label: 'Change vs prior quarter (%)' },
    signal: 'Entered as change against the prior quarter.',
  },
  {
    id: 'FIN_04',
    quadrant: 'financial',
    icon: '🔒',
    label: 'Licence-line price discipline',
    short: 'Price discipline',
    definition: 'Number of reactive licence-price cuts in period.',
    source: 'Pricing log',
    sourceId: 'pricing-log',
    owner: 'Strategy',
    freq: 'Monthly',
    baseline: { display: 'Held', value: 0 },
    target: { display: '0 cuts', value: 0 },
    thresholds: 'Any cut red',
    rule: { kind: 'zero' },
    scale: { min: 0, max: 5, unit: 'cuts' },
    input: { type: 'count', max: 5, label: 'Reactive licence-price cuts this period' },
    signal: 'Held at baseline.',
  },
  // ---- Learning & growth ---------------------------------------------------
  {
    id: 'LG_01',
    quadrant: 'learning',
    icon: '👤',
    label: 'Named-owner coverage',
    short: 'Named owners',
    definition: '% of active SME clients with a named account owner recorded in CRM.',
    source: 'CRM',
    sourceId: 'crm',
    owner: 'Customer success',
    freq: 'Monthly',
    baseline: { display: 'Partial', value: null },
    target: { display: '100% in 6 months', value: 100 },
    thresholds: '<50 red; 50–89 amber; ≥90 green',
    rule: { kind: 'higher', red: 50, amber: 90 },
    scale: { min: 0, max: 100, unit: '%' },
    input: { type: 'range', min: 0, max: 100, step: 1, label: 'Active SME clients with a named owner (%)' },
    signal: 'Partial today — not yet quantified.',
  },
  {
    id: 'LG_02',
    quadrant: 'learning',
    icon: '🎙️',
    label: 'CSP script adherence',
    short: 'Script adherence',
    definition: 'Mystery-shop score against the value-led script (0–100).',
    source: 'Quarterly internal mystery shop',
    sourceId: 'mystery-shop',
    owner: 'Sales ops',
    freq: 'Quarterly',
    baseline: { display: '—', value: null },
    target: { display: '≥85', value: 85 },
    thresholds: '<60 red; 60–84 amber; ≥85 green',
    rule: { kind: 'higher', red: 60, amber: 85 },
    scale: { min: 0, max: 100, unit: '/100' },
    input: { type: 'range', min: 0, max: 100, step: 1, label: 'Script adherence score (0–100)' },
    signal: 'Value anchor · all-in quote · named owner.',
  },
  {
    id: 'LG_03',
    quadrant: 'learning',
    icon: '🔎',
    label: 'rakez.com in top-3 for cost queries',
    short: 'Top-3 cost queries',
    definition: "Rank for 'RAKEZ cost', 'RAKEZ vs IFZA', 'RAKEZ hidden fees', 'RAKEZ licence price'.",
    source: 'Search Console / rank tracker',
    sourceId: 'rank-tracker',
    owner: 'Marketing',
    freq: 'Monthly',
    baseline: { display: 'No', value: 0, detail: 'agents rank above' },
    target: { display: 'Top-3 on all 4 in 6 months', value: 4 },
    thresholds: '0–1 red; 2–3 amber; 4 green',
    rule: { kind: 'higher', red: 2, amber: 4 },
    scale: { min: 0, max: 4, unit: '/4' },
    input: { type: 'count', max: 4, label: 'Queries where rakez.com ranks top-3' },
    signal: 'Agents rank above rakez.com on all four queries.',
  },
  {
    id: 'LG_04',
    quadrant: 'learning',
    icon: '🪜',
    label: 'Partner tier movement',
    short: 'Tier movement',
    definition: 'Number of partners moving up a tier ÷ total tiered partners.',
    source: 'Channel',
    sourceId: 'mystery-shop',
    owner: 'Channel',
    freq: 'Quarterly',
    baseline: { display: '—', value: null },
    target: { display: 'Net positive', value: 1 },
    thresholds: 'Net negative red',
    rule: { kind: 'sign' },
    scale: { min: -5, max: 5, unit: 'net' },
    input: { type: 'range', min: -5, max: 5, step: 1, label: 'Net partners moving up a tier' },
    signal: 'Follows the partner leaderboard from the mystery shop.',
  },
]

// ---------------------------------------------------------------------------
// Pilot plan: the data sources that make every tile sourceable (spec §8),
// modelled as dependency-locked steps. A tile accepts a demo entry only once
// its source step is live. `done` at baseline = a figure already exists.
// ---------------------------------------------------------------------------
export const SOURCES = [
  {
    id: 'dictionary',
    icon: '📖',
    title: 'Lock the KPI dictionary',
    short: 'Dictionary',
    time: 'Half a day',
    owner: 'Marketing',
    cadence: 'Once; change-controlled',
    needs: ['KPI_ID per tile', 'Red_below / Amber_below thresholds', 'Named owner per KPI'],
    tip: 'Definitions change only via the dictionary with a dated note — never edit historical values.',
    deps: [],
    feeds: [],
  },
  {
    id: 'crm',
    icon: '🗂️',
    title: 'Set up the CRM monthly export',
    short: 'CRM export',
    time: '1–2 days with sales ops',
    owner: 'Sales ops',
    cadence: 'Export monthly',
    needs: ['Qualified-enquiry flag', 'Quote-sent timestamp', 'Named account owner field'],
    tip: 'Conversion is registrations ÷ qualified enquiries on a trailing 3 months — a single month swings too much to act on.',
    deps: ['dictionary'],
    feeds: ['HERO_03', 'PROC_03', 'LG_01'],
  },
  {
    id: 'telephony',
    icon: '☎️',
    title: 'Export the telephony log weekly',
    short: 'Telephony log',
    time: '1 day',
    owner: 'Sales ops',
    cadence: 'Export weekly',
    needs: ['Inbound sales queue ID', 'Rings-to-answer field'],
    tip: 'Measure the sales queue only — mixing in support calls flatters the number.',
    deps: ['dictionary'],
    feeds: ['PROC_02'],
  },
  {
    id: 'quote-audit',
    icon: '🧾',
    title: 'Run the monthly quote audit',
    short: 'Quote audit',
    time: '2 hours a month',
    owner: 'Marketing + Sales',
    cadence: '10 enquiries a month',
    needs: ['Price of record per package', '10 random first written quotes', 'The 5 standard extras checklist'],
    tip: 'Audit the first written quote, not the final one — that is what the prospect compares against IFZA.',
    deps: ['dictionary'],
    feeds: ['CUST_02', 'PROC_01'],
  },
  {
    id: 'gbp',
    icon: '⭐',
    title: 'Read the Google Business Profile',
    short: 'Google profile',
    time: '15 min a month',
    owner: 'Marketing',
    cadence: 'Read monthly',
    needs: ['Profile manager access', 'Rating distribution export'],
    tip: 'Record the distribution, not just the average — the 1★ band feeds the Advocacy dimension.',
    deps: ['dictionary'],
    feeds: ['HERO_02'],
  },
  {
    id: 'trustpilot',
    icon: '🛡️',
    title: 'Claim the Trustpilot profile',
    short: 'Trustpilot',
    time: '1 day',
    owner: 'Marketing',
    cadence: 'Claim; read monthly',
    needs: ['Business email verification', 'Reply policy for existing reviews'],
    tip: 'Claiming moves the tile from red to amber on its own; the rating only moves once you reply and invite.',
    deps: ['dictionary'],
    feeds: ['CUST_03'],
  },
  {
    id: 'rank-tracker',
    icon: '🔎',
    title: 'Track the four cost queries',
    short: 'Rank tracker',
    time: 'Half a day',
    owner: 'Marketing',
    cadence: 'Monthly',
    needs: ['Search Console access', 'Rank tracker with the 4 saved queries'],
    tip: "Track 'RAKEZ hidden fees' too — that is the query agents win today.",
    deps: ['dictionary'],
    feeds: ['LG_03'],
  },
  {
    id: 'finance',
    icon: '📒',
    title: 'Add three lines to the monthly close',
    short: 'Finance close',
    time: 'One close cycle',
    owner: 'Finance',
    cadence: 'Monthly close',
    needs: ['Marketing + commission + sales cost by month', 'SME registrations by channel', 'Commission split: at signing vs at renewal'],
    tip: 'Cost per acquired SME needs three months before thresholds are set — publish the trend, not a verdict.',
    deps: ['dictionary'],
    feeds: ['FIN_01', 'FIN_02', 'FIN_03'],
  },
  {
    id: 'compliance',
    icon: '📅',
    title: 'Wire compliance alerts to the client roster',
    short: 'Compliance alerts',
    time: '1–2 weeks with IT',
    owner: 'Compliance',
    cadence: 'Monthly',
    needs: ['Corporate-tax registration and renewal dates', 'Client roster with named owners from CRM'],
    tip: '≥30 days means the alert date, not the deadline date — log both.',
    deps: ['crm'],
    feeds: ['PROC_04'],
  },
  {
    id: 'mystery-shop',
    icon: '🕵️',
    title: 'Run the partner mystery shop',
    short: 'Mystery shop',
    time: '1 week a quarter',
    owner: 'Channel',
    cadence: 'Quarterly',
    needs: ['Top-10 partners by volume + 5 random', 'GIP III persona script (15 questions)', 'Two-coder scoring sheet'],
    tip: 'Log whether the partner names RAKEZ before the prospect does — prompting it yourself counts as no.',
    deps: ['dictionary'],
    feeds: ['CUST_01', 'LG_02', 'LG_04'],
  },
  {
    id: 'be-rescoring',
    icon: '🧮',
    title: 'Re-score Brand Equity',
    short: 'BE re-score',
    time: 'Half a day, two coders',
    owner: 'Marketing',
    cadence: 'Quarterly → annual',
    needs: ['Review count and distribution', 'Mystery-shop tally', 'Coded review themes'],
    tip: 'Two people score blind; reconcile differences by evidence, never by averaging.',
    deps: ['gbp'],
    feeds: ['HERO_01'],
  },
  {
    id: 'pricing-log',
    icon: '🏷️',
    title: 'Keep the licence pricing log',
    short: 'Pricing log',
    time: 'Ongoing',
    owner: 'Strategy',
    cadence: 'Monthly',
    needs: ['Every licence-price change with date and reason'],
    tip: "A reactive cut logged as a 'promotion' is still a cut.",
    deps: ['dictionary'],
    feeds: ['FIN_04'],
  },
  {
    id: 'industry-data',
    icon: '📈',
    title: 'Compile UAE free-zone registration share',
    short: 'Industry data',
    time: '1 day a quarter',
    owner: 'Strategy',
    cadence: 'Quarterly',
    needs: ['RAKEZ new registrations', 'UAE free-zone total from industry data'],
    tip: "Use the same definition of 'new registration' on both sides of the ratio.",
    deps: ['dictionary'],
    feeds: ['CUST_04'],
  },
]

// Pre-loaded persona, mid-pilot, so the demo looks alive on first open.
export const PERSONA = {
  name: 'Layla',
  bio: 'Head of Commercial · sample persona',
  answers: { role: 'leadership', cadence: 'monthly', focus: 'HERO_01' },
  done: ['dictionary', 'crm', 'gbp', 'be-rescoring', 'pricing-log', 'industry-data'],
}

// ---------------------------------------------------------------------------
// Brand Equity re-scoring worksheet (spec §6). Baseline scores are a sample
// reconstruction consistent with the 48 composite — replace with Appendix B.
// ---------------------------------------------------------------------------
export const BE_DIMENSIONS = [
  {
    id: 'awareness',
    label: 'Awareness',
    weight: 0.2,
    rules: { 5: '>2,500 reviews or unprompted CSP reference', 4: '500–2,500 reviews or top-3 share', 3: 'Recognised when prompted', 2: 'Thin footprint' },
    evidence: 'Review count; share; CSP mentions',
    baseline: 4,
    baselineNote: '520 reviews; ~19% share',
  },
  {
    id: 'consideration',
    label: 'Consideration',
    weight: 0.2,
    rules: { 5: 'Unprompted by CSPs and dominant in agent content', 4: 'Unprompted by one CSP', 3: 'Offered as an alternative', 2: 'Only when prompted' },
    evidence: 'Partner mystery-shop tally; search audit',
    baseline: 2,
    baselineNote: '0 of 2 CSPs named RAKEZ unprompted',
  },
  {
    id: 'quality',
    label: 'Perceived quality',
    weight: 0.25,
    rules: { 5: '≥4.8', 4: '4.5–4.7', 3: '4.2–4.4', 2: '3.5–4.1' },
    evidence: 'Google aggregate rating',
    baseline: 2,
    baselineNote: 'Google 3.7',
  },
  {
    id: 'associations',
    label: 'Associations',
    weight: 0.2,
    rules: { 5: 'Uniformly positive', 4: 'Positive dominant', 3: 'Agent-authored positives only', 2: 'Recurring customer negatives' },
    evidence: 'Coded themes, customer vs agent',
    baseline: 2,
    baselineNote: 'Sample — score from coded themes',
  },
  {
    id: 'advocacy',
    label: 'Advocacy',
    weight: 0.15,
    rules: { 5: '1★ sliver + named-staff praise', 4: 'Strong but lower', 3: '—', 2: '1★ second-largest band' },
    evidence: 'Rating distribution; Trustpilot',
    baseline: 2,
    baselineNote: 'Trustpilot 2.6, unclaimed',
  },
]

// Benchmark chart (spec §3). RAKEZ figures are the spec baselines; peer
// values are ILLUSTRATIVE placeholders to be replaced from GIP III evidence.
export const BENCHMARK = {
  target: 70,
  zones: [
    { zone: 'IFZA', be: 62, google: 4.4, illustrative: true },
    { zone: 'Meydan', be: 58, google: 4.2, illustrative: true },
    { zone: 'SHAMS', be: 45, google: 3.9, illustrative: true },
    { zone: 'DMCC', be: 71, google: 4.5, illustrative: true },
    { zone: 'RAKEZ', be: 48, google: 3.7, illustrative: false },
  ],
}

// Mystery-shop protocol (spec §7).
export const SHOP_PROTOCOL = {
  sample: 'Top-10 partners by volume + 5 random, quarterly.',
  persona: 'GIP III profile — Indian founder, general trading, one visa. Same 15 questions as Appendix A1.',
  record: [
    'Did the partner name RAKEZ before the prospect did?',
    'Headline price quoted vs price of record',
    'Number of standard extras disclosed unprompted',
    'Script elements used: value anchor, all-in quote, named owner',
  ],
  outputs: ['Unprompted-recommendation rate', 'Price-match %', 'Script adherence score'],
  scriptElements: [
    { id: 'anchor', label: 'Value anchor' },
    { id: 'allin', label: 'All-in quote' },
    { id: 'owner', label: 'Named owner' },
  ],
}

// Sample partner names for the log form (invented).
export const SAMPLE_PARTNERS = ['Marina Setup Co.', 'Gulf Gateway Advisors', 'Northstar Formations', 'Falcon Corporate Services', 'BlueSand Business Hub']

// Three build options (spec §2).
export const BUILD_OPTIONS = [
  {
    id: 'A',
    icon: '🖼️',
    name: 'A — Static mock-up',
    tool: 'PowerPoint, or a screenshot of this HTML mock-up',
    when: 'Final presentation slide 18; sponsor discussion',
    effort: '2 hours',
    features: ['3 hero numbers, 16 tiles, 1 chart', 'Sep 2026 baselines', 'Slide view in this demo'],
    role: 'Deliver for the review',
  },
  {
    id: 'B',
    icon: '📊',
    name: 'B — Working scorecard',
    tool: 'Excel: Data tab + KPI_Dictionary tab + Dashboard tab',
    when: 'RAKEZ pilot, first 3 months, manual monthly entry',
    effort: '1 day',
    features: ['XLOOKUP tiles from the Data tab', 'Status formula per tile', 'Conditional RAG formatting', 'BE_Rescoring sheet'],
    role: 'Hand over as the pilot artefact',
    recommended: true,
  },
  {
    id: 'C',
    icon: '🔌',
    name: 'C — Live dashboard',
    tool: 'Power BI / Looker Studio on CRM, telephony and Google exports',
    when: 'After the pilot proves the KPIs are sourceable',
    effort: '1–2 weeks with RAKEZ IT',
    features: ['Automated refresh', 'Drill-through to source rows', 'Weekly SLA tiles live'],
    role: 'Scope as the 6-month step',
  },
]

export const EXCEL_DATA_COLUMNS = [
  ['Period', 'yyyy-mm', '2026-10'],
  ['KPI_ID', 'text key from dictionary', 'CUST_02'],
  ['Value', 'number / text', '0.62'],
  ['Numerator', 'number (optional)', '31'],
  ['Denominator', 'number (optional)', '50'],
  ['Source_ref', 'text', 'Quote audit Oct-26'],
  ['Entered_by', 'text', 'Sales ops'],
  ['Note', 'text', '3 CSPs retrained'],
]

// Refresh cadence and governance (spec §9).
export const GOVERNANCE = {
  cadence: [
    { icon: '⚡', label: 'Weekly', text: 'Sales ops updates the two SLA tiles.' },
    { icon: '📅', label: 'Monthly', text: 'Full refresh by the 5th working day; 30-minute review with commercial leadership.' },
    { icon: '🔬', label: 'Quarterly', text: 'Partner mystery shop and Brand Equity re-score.' },
  ],
  changeControl: 'KPI definitions change only via the dictionary with a dated note; never edit historical values.',
  mockupNote: 'This HTML mock-up carries the Sep 2026 baselines for screenshot or live demo; it is static and does not read RAKEZ data.',
}

// ---------------------------------------------------------------------------
// Scroll scenes. Each maps a section of the scorecard to a building image.
// Drop a real photograph at src/assets/photos/<file> and set `credit` to show
// it; until then the generated skyline plate is used and labelled as such.
// ---------------------------------------------------------------------------
export const SCENES = [
  { id: 'corniche', title: 'RAK Free Trade Zone Authority HQ', file: 'rakez-hq.webp', credit: 'Photo supplied by RAKEZ', focus: '50% 40%', zoom: 1, style: 'city', palette: ['#0b1e3a', '#3a5f8a', '#f0a35c'] },
  { id: 'al-hamra', title: 'HQ · the RAK towers', file: 'rakez-hq.webp', credit: 'Photo supplied by RAKEZ', focus: '78% 30%', zoom: 1.35, style: 'towers', palette: ['#10233f', '#1f3a5f', '#e9b872'] },
  { id: 'business-zone', title: 'HQ · Free Trade Zone entrance', file: 'rakez-hq.webp', credit: 'Photo supplied by RAKEZ', focus: '22% 62%', zoom: 1.45, style: 'offices', palette: ['#0f2a33', '#2a7d8c', '#d9e6ea'] },
  { id: 'industrial', title: 'HQ · east wing', file: 'rakez-hq.webp', credit: 'Photo supplied by RAKEZ', focus: '92% 55%', zoom: 1.5, style: 'sheds', palette: ['#2b1d16', '#7a4a2b', '#f2c58a'] },
  { id: 'academic', title: 'HQ · the palm forecourt', file: 'rakez-hq.webp', credit: 'Photo supplied by RAKEZ', focus: '40% 85%', zoom: 1.4, style: 'campus', palette: ['#132238', '#4b6d8c', '#f6d7a5'] },
  { id: 'mountains', title: 'HQ · full elevation', file: 'rakez-hq.webp', credit: 'Photo supplied by RAKEZ', focus: '50% 55%', zoom: 1.08, style: 'mountains', palette: ['#1a1330', '#5c3b5e', '#f39c6b'] },
]
